---
ignored:
  - DL3008 # DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install
  - DL3006 # Always tag the version of an image explicitly
  - DL3007 # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
 #  - DL3015 # Avoid additional packages by specifying `--no-install-recommends`
  - DL3016 # Pin versions in npm. Instead of `npm install <package>` use `npm install <package>@<version>`
  - DL3018 # Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
  - DL3013 # Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<>`
  - DL3022 # DL3022 COPY --from should reference a previously defined FROM alias
  - DL3028 # DL3028 Pin versions in gem install
