branches:
  - "master"

tagFormat: v${version}
repositoryUrl: https://gitlab.com/donaldrich/cicdevs.git
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: test
          release: minor
        - type: ci
          release: minor
        - type: chore
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: fixed
            section: Fixed
          - type: fix
            section: Bug Fixes
          - type: added
            section: Added
          - type: feat
            section: Features
          - type: changed
            section: Changed
          - type: removed
            section: Removed
          - type: ci
            section: Continuous Integration
            hidden: true
          - type: build
            section: Build System
            hidden: true
          - type: test
            section: Tests
            hidden: true
          - type: improved
            section: Improved
          - type: chore
            section: Maintainence
            hidden: true
    # { type: 'feat', section: 'Features' },
    # { type: 'feature', section: 'Features' },
    # { type: 'perf', section: 'Performance Improvements' },
    # { type: 'revert', section: 'Reverts' },
    # { type: 'docs', section: 'Documentation', hidden: true },
    # { type: 'style', section: 'Styles', hidden: true },
    # { type: 'refactor', section: 'Code Refactoring', hidden: true },

  - "@semantic-release/gitlab"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG
# plugins:
#   - - "@semantic-release/commit-analyzer"
#     - preset: conventionalcommits
#       releaseRules:
#         - type: added
#           release: minor
#         - type: fixed
#           release: patch
#         - type: changed
#           release: patch
#         - type: removed
#           release: minor
#         - type: ci
#           release: patch
#         - scope: improved
#           release: patch
#         - type: chore
#           release: false

#       parserOpts:
#         noteKeywords:
#           - BREAKING CHANGE
#           - BREAKING CHANGES
#           - BREAKING
#       parserOpts:
#         noteKeywords:
#           - BREAKING CHANGE
#           - BREAKING CHANGES
#           - BREAKING
#   - "@semantic-release/gitlab"
#   - - "@semantic-release/changelog"
#     - changelogFile: CHANGELOG
#   - - "@semantic-release/git"
#     - assets:
#         - CHANGELOG
#       message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
