version: "3"

tasks:
  commit:
    deps: [deps, test]
    cmds:
      - git pull origin master
      - git add .
      - 'git commit -m "chore(repo): auto message"'
      - git push origin master
      - git push github master

  build:
    deps: [deps, clean]
    cmds:
      - mkdir docs | true
      - cp .meta/docs/index.md docs
      - cp -r .meta/docs/about docs
      - cp CHANGELOG docs/about
      - ./run-all.sh

  test:
    deps: [deps, build]
    cmds:
      - pre-commit install
      - pre-commit autoupdate
      # - pre-commit install --hook-type commit-msg
      # - pre-commit install --hook-type prepare-commit-msg
      - pre-commit run -a || true

  clean:
    cmds:
      - rm -r docs | true
      - rm -r .meta/pipelines | true
    status:
      - "-f docs"
      - "-f .meta/pipelines"

  deps:
    cmds:
      - echo "install gomplate"
      - sudo pip3 install pre-commit
      - echo "install buildx"
    status:
      - gomplate -v
      - pre-commit -V
      - docker buildx version

  # - args:
  #     - merge
  #     - -a
  #   description: Use yq
  #   entry: --entrypoint yq mikefarah/yq
  #   files: git-hooks.yml
  #   id: hook-test
  #   language: docker_image
  #   log_file: .pre-commit-hooks.yaml
