base:python.opensuse:
  stage: build
  trigger:
    include: .meta/pipeline/base/python/opensuse/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "base/python/opensuse/Dockerfile"
        - "base/python/opensuse/goss.yaml"
        - "base/python/opensuse/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "python.opensuse"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
