base:opensuse.tumbleweed:
  stage: build
  trigger:
    include: .meta/pipeline/base/opensuse/tumbleweed/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "base/opensuse/tumbleweed/Dockerfile"
        - "base/opensuse/tumbleweed/goss.yaml"
        - "base/opensuse/tumbleweed/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "opensuse.tumbleweed"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
