
# ENV     DOCKER_MACHINE_VERSION=0.16.2
# ENV     DOCKER_MACHINE_SHA256=a7f7cbb842752b12123c5a5447d8039bf8dccf62ec2328853583e68eb4ffb097
# SHELL   ["/bin/bash", "-o", "pipefail", "-c"]
# RUN     wget "https://github.com/docker/machine/releases/download/v${DOCKER_MACHINE_VERSION}/docker-machine-Linux-x86_64" -O /usr/local/bin/docker-machine \
#   && echo "${DOCKER_MACHINE_SHA256} */usr/local/bin/docker-machine" | sha256sum -c - \
#   && chmod +x /usr/local/bin/docker-machine \
#   && upx /usr/local/bin/docker-machine
# ddd
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- \
    -t agnoster
    # -p git \
    # -p ssh-agent \
    # -p https://github.com/zsh-users/zsh-autosuggestions \
    # -p https://github.com/zsh-users/zsh-completions


# RUN sh -c "$(wget -O- https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- \
#     -t agnoster
# -p git \
# -p ssh-agent \
# -p https://github.com/zsh-users/zsh-autosuggestions \
# -p https://github.com/zsh-users/zsh-completions

# RUN zsh