terraform:full:
  stage: build
  trigger:
    include: .meta/pipeline/hashicorp/terraform/full/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "hashicorp/terraform/full/Dockerfile"
      - "hashicorp/terraform/full/goss.yaml"
      - "hashicorp/terraform/full/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "terraform" && $TRIGGER_VAR2 == "full"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "terraform" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
