FROM donaldrich/hexo:latest

RUN \
 # apt-get update && \
 # apt-get install git -y && \
npm install hexo-theme-icarus
 # npm install -g hexo-cli
# npm install bulma-stylus \
# npm install deepmerge \
# npm install hexo \
# npm install hexo-component-inferno \
# npm install hexo-log \
# npm install hexo-pagination \
# npm install hexo-renderer-inferno \
# npm install hexo-renderer-stylus \
