packer:latest:
  stage: build
  trigger:
    include: .meta/pipeline/hashicorp/packer/latest/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "hashicorp/packer/latest/Dockerfile"
        - "hashicorp/packer/latest/goss.yaml"
        - "hashicorp/packer/latest/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "packer" && $TRIGGER_VAR2 == "latest"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "packer" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
