builder:bazel:
  stage: build
  trigger:
    include: .meta/pipeline/builder/bazel/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "builder/bazel/Dockerfile"
      - "builder/bazel/goss.yaml"
      - "builder/bazel/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "builder" && $TRIGGER_VAR2 == "bazel"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "builder" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
