include:
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/pushover/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/default.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/healthchecks/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/lint.yml

build:ansible:latest:
  extends:
    - .dockerhub:monoarch:push

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - documentation
  - notify

variables:
  DOCKER_BUILD_DIR: ansible/latest
  IMAGE_NAME: ansible
  IMAGE_TAG: latest
  DOCKERFILE: Dockerfile
  DOCKER_BUILD_CONTEXT: ansible/latest
  PUSHOVER_ID: $IMAGE_NAME:$IMAGE_TAG
