include:
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/pushover/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/default.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/healthchecks/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/lint.yml

build:base:google.ubuntu:
  extends:
    - .dockerhub:monoarch:push

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - documentation
  - notify

variables:
  DOCKER_BUILD_DIR: base/google/ubuntu
  IMAGE_NAME: base
  IMAGE_TAG: google.ubuntu
  DOCKERFILE: Dockerfile
  DOCKER_BUILD_CONTEXT: base/google/ubuntu
  PUSHOVER_ID: $IMAGE_NAME:$IMAGE_TAG
