base:google.ubuntu:
  stage: build
  trigger:
    include: .meta/pipeline/base/google/ubuntu/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "base/google/ubuntu/Dockerfile"
        - "base/google/ubuntu/goss.yaml"
        - "base/google/ubuntu/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "google.ubuntu"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
