base:debian:
  stage: build
  trigger:
    include: .meta/pipeline/base/debian/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "base/debian/Dockerfile"
        - "base/debian/goss.yaml"
        - "base/debian/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "debian"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
