include:
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/pushover/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/default.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/healthchecks/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/lint/docker.yml

build:mkdocs:mkpdfs:
  extends:
    - .dockerhub:monoarch:push

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - documentation
  - notify

variables:
  DOCKER_BUILD_DIR: site-gen/mkdocs/mkpdfs
  IMAGE_NAME: mkdocs
  IMAGE_TAG: mkpdfs
  DOCKERFILE: Dockerfile
  DOCKER_BUILD_CONTEXT: site-gen/mkdocs/mkpdfs
  PUSHOVER_ID: $IMAGE_NAME:$IMAGE_TAG
