base:alpine:
  stage: build
  trigger:
    include: .meta/pipeline/base/alpine/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "base/alpine/Dockerfile"
      - "base/alpine/goss.yaml"
      - "base/alpine/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "alpine"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
