base:centos:
  stage: build
  trigger:
    include: .meta/pipeline/base/centos/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "base/centos/Dockerfile"
        - "base/centos/goss.yaml"
        - "base/centos/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "centos"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "base" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
