ansible:base:
  stage: build
  trigger:
    include: .meta/pipeline/ansible/base/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "ansible/base/Dockerfile"
        - "ansible/base/goss.yaml"
        - "ansible/base/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "ansible" && $TRIGGER_VAR2 == "base"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "ansible" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
