include:
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/pushover/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/default.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/notifications/healthchecks/docker-build.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/docker/lint.yml

build:naturaldocs:latest:
  extends:
    - .dockerhub:monoarch:push

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - documentation
  - notify

variables:
  DOCKER_BUILD_DIR: site-gen/natural_docs
  IMAGE_NAME: naturaldocs
  IMAGE_TAG: latest
  DOCKERFILE: Dockerfile
  DOCKER_BUILD_CONTEXT: site-gen/natural_docs
  PUSHOVER_ID: $IMAGE_NAME:$IMAGE_TAG
