naturaldocs:latest:
  stage: build
  trigger:
    include: .meta/pipeline/site-gen/natural_docs/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "site-gen/natural_docs/Dockerfile"
        - "site-gen/natural_docs/goss.yaml"
        - "site-gen/natural_docs/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "naturaldocs" && $TRIGGER_VAR2 == "latest"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "naturaldocs" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
