ansible:full:
  stage: build
  trigger:
    include: .meta/pipeline/ansible/full/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "ansible/full/Dockerfile"
        - "ansible/full/goss.yaml"
        - "ansible/full/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "ansible" && $TRIGGER_VAR2 == "full"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "ansible" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
